version: '3'
services:
  # db is is db folder
  db:
    image: 40501792test.azurecr.io/db
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"

  # Application Dockerfile is in same folder which is .
  app:
    image: 40501792test.azurecr.io/app
    build: .
    restart: on-failure
    ports:
      - "8080:8080"

  nginx:
    image: 40501792test.azurecr.io/nginx
    build: web/.
    ports:
      - "80:80"

