version: '3'
services:
  # Application Dockerfile is in same folder which is .
  app:
    image: 40501792test.azurecr.io/app
    build: .
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    depends_on:
      - db

  # db is is db folder
  db:
    image: 40501792test.azurecr.io/db
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "33060:3306"
  nginx:
    image: 40501792test.azurecr.io/nginx
    build: web/.
    ports:
      - "80:80"
    depends_on:
      - app
